### ISSUE TITLE
UGT için #ugtnot etiketini resmi hashtag yapmak için uygun mudur?

### ISSUE THREAD

**Issue by byneu** [UJazza/social-media-improvisation#1]
#etiket *(hashtag)* günümüz web platformlarında içeriğe ID verilmesidir. Pratik ID ya da bildiğimiz etiket yöntemi, platformların öncelikle kullandığı bir listeleme *(sort)* kolaylığı da sağlamıştır. Yani etiketleme, içeriklerin taranıp listelenmesinde internet kullanıcıları ve platform bilgi sistemine avantajlar getirmektedir.

## Amaç

**İçeriklerde en az harfden oluşan #etiket kullanımı ile** tüm platformdaki; 

1. etkileşimleri 

2. geri bildirimleri sınıflandırmak, gruplamak 

3. **Araştırma** başlığında kullanılan sosyal medya search URL ler ile kullanıcıların web browser üzerinden herhangi bir şifre ya da aplikasyon kullanma şartına bağlı olmadan görüntülenmesini sağlamak

amacındayım. 

Böylece herkesin kullanmaya alışık olduğu tüm platformlardan _(e-mail, sosyal medya vb)_ bu etiket ile yorum yazdıklarında dikkate alınacağını bilmelerini sağlamak. Onları #etiket kullandırmaya yönlendirmek. 

## Araştırma
Twitter üzerinde yaptığım araştırmalar sonucunda sırayla olması gereken kısa #etiket adları ve parantez içerisinde ise kaç kez kullanıldığını belirttim. Yani #etiket (Twitter kullanıcı sayısı - Instagram post sayısı - Facebook sayıları)

#ugtnot (1-0-0) 
#unotes (10-288-16) 
#ugtn (51-1-15) 
#mugt (42-0-63)

**Araştırma verilerine bakarak en uygun, hiç kullanılmayan ve anlaşılır etiket: #ugtnot**

https://m.facebook.com/search/?search=people&search_source=search_bar&query=%23ugtnot&=Ara
https://twitter.com/search?f=tweets&q=%23ugtnot&src=typd
https://www.instagram.com/explore/tags/ugtnot/

## Soru
UGT için #ugtnot etiketini resmi hashtag yapmak için uygun mudur?

**Comment by mertizcan** [comment]
Esasında uygun bir tek İngilizce'de 'negatiflik' olan -not- kelimesi olmasına emin olamadım. Markalandırma yöntemimize de dikkat etmek gerekir. U'Notes U'Jazza U'Forum bu noktaya uyumlu isimlendirme pratiğimiz. Gerçi diğer markalandırma Türkçe'ye daha uygun isimlendirme de Sinema Müzik Bisiklet..UGT  konu+UGT formülünü uygulamışız. NotUGT daha uygun ama bu sefer İngilizce'deki negatifleme tam oluyor. Belki Not yerine farklı bir isim mi düşünsek?

**Comment by byneu** [comment]
## #ugtnotu
Farklı sosyal medya kullanıcılarına not _(aslında geri bildirim)_ yazmaları ve bu etiket ile de içeriklerimizi listeyebilme kolaylığını hayatlarına geçirmeyi planlıyorum. Ve UGT sosyal medyasının yayınladığı içerik dili Tükçe olduğu için **not** kelimesi olumsuzluğu akla getirmeyecektir. Yine de bu düşünceni dikkate alarak **#ugtnotu** etiket ismi de alternatif olabilir. #unotes etiketi tüm dünyada "üniversite notları" olarak tanımlanmış olduğundan şimdilik U'Notes markamız ile pek özdeş değil; hatta, çok post olduğu için arada kaynama şansı çok yüksek. **#ugtnot** veya **#ugtnotu** etiketinin tek avantajı hiç kullanılmamış ve tertemiz olmasıdır. Bu avantajdır.

**Comment by byneu** [comment]
@mertizcan #ugtnot veya #ugtnotu etiketi içeren sosyal medya paylaşımı hiç olmamıştır. Hiç kullanılmamış, tertemiz olması neden ile son görüşünü almak isterim.

**Comment by mertizcan** [comment]
@byneu  #ugtnotu'na daha anlamlı geliyor bana sadece İngilizce konusu değil. Sesli söylediğimde de daha uygun geliyor kulağıma. İkisinin de kullanılmamış olması büyük avantaj tabi.

**Comment by byneu** [comment]
#ugtnotu etiketini kullaniyoruz.
